python/karaoke/karaoke/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^songs/', include('songs.urls', namespace='songs')),
    url(r'^$', views.home, name='home'),
]

python/karaoke/songs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'performer/(?P<pk>\d+)/$', views.performer_detail, name='performer'),
    url(r'song/(?P<pk>\d+)/$', views.song_detail, name='detail'),
    url(r'', views.song_list, name='list'),
]

python/karaoke/songs/models.py
from django.db import models

# Write your models here

python/karaoke/karaoke/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

python/karaoke/songs/views.py
from django.shortcuts import render

python/karaoke/songs/templates/songs/performer_detail.html
{% extends 'base.html' %}

{% block title %}{{ performer }}{% endblock %}

{% block content %}
<h2>{{ performer }}</h2>
{% endblock %}

python/karaoke/songs/templates/songs/song_detail.html
{% extends 'base.html' %}

{% block title %}{{ song.title }}{% endblock %}

{% block content %}
<h2>{{ song.title }}</h2>

<p>By {{ song.artist }}</p>
<p>Sung by <a href="{% url 'songs:performer' pk=song.performer.pk %}">{{ song.performer }}</a></p>
{% endblock %}

python/karaoke/songs/templates/songs/song_list.html
{% extends 'base.html' %}

{% block title %}Upcoming Songs{% endblock %}

{% block content %}
<h2>Upcoming Songs</h2>

<ul>
    {% for song in songs %}
    <li><a href="{% url 'songs:detail' pk=song.pk %}">{{ song }}</a> performed by <a href="{% url 'songs:performer' pk=song.performer.pk %}">{{ song.performer }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

python/karaoke/templates/base.html
<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %} - Django Karaoke</title>
    </head>
    <body>
        <h1>Django Karaoke!</h1>
        <p><a href="{% url 'songs:list' %}">Upcoming Songs</a></p>
        
        {% block content %}{% endblock %}
    </body>
</html>

python/karaoke/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}